### ISSUE TITLE
Emphasize that source code is not the DOM

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js_intro_jquery#11]
The DOM is an object the browser creates by reading source code.

Sometimes there is confusion about why changing something in the inspector doesn't persist between browser refreshes.

It's a good teachable moment about how browsers work (requests end with a response that has source, you can't edit a file on someone else's server can you? etc. etc.)

**Comment by jrhorn424** [comment]
During the presentation today, we had to re-emphasize that source code is not the DOM, and the DOM is not the rendered page. It's a step in-between.

We removed a video for time. It should be included in the pre-readings assignment. https://www.youtube.com/watch?v=n1cKlKM3jYI

**Comment by payne-chris-r** [comment]
Fixed in latest commit. Video is ALSO added to Study
