### ISSUE TITLE
Emphasize that jQuery does iteration for you

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js_intro_jquery#12]
Trying to mix jQuery with JavaScript language features is, in general, a smell. The specific case where this bites people is:
- Thinking a jQuery object is an array and has array methods (it has some, but not all)
- Attaching a click handler in a loop fails (because, closure), but it's also not necessary, since if you use `.on('click')` instead of `.click()`, jQuery will attach the eventHandler on every single node in the jQuery object

**Comment by raq929** [comment]
@jrhorn424 - Do you have a suggestion for where to incorporate this into the lesson?

**Comment by jrhorn424** [comment]
A gotchas section, at the end of the README, before the "Additional Resources" section, is a good place for now! Thanks for following up.
