### ISSUE TITLE
Add a best practices list

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js_intro_jquery#13]
Some things to include:
- prefer `.on('click')` to `.click()`
- prefer `$.ajax()` with the deferred object interface (don't use `$.get` and friends since it use arguments instead of "promise")

**Comment by payne-chris-r** [comment]
@jrhorn424 I'm happy to add this, and think I mentioned it last time, but I'd love to put a solid reason behind why `.on('click',...) > .click()` in the README if possible.

**Comment by jrhorn424** [comment]
Pedagogically, it gets them thinking about events. It's less magic. More importantly, we can't take advantage of bubbling to event delegation with `click`. Compare the signatures:
1. https://api.jquery.com/click/
2. http://api.jquery.com/on/
