### ISSUE TITLE
Move this to ajax lesson?

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js_intro_jquery#24]
-   Use `$.ajax()` over `$.get()`. The `$.ajax` version is preferable because
  of its use of `promises` which we'll cover later on in the course.

This is in the best practices section of the README, but this lesson is before the ajax lessons, so I don't think it makes much sense here.

**Comment by gaand** [comment]
@raq929 It's also doesn't apply until we're using jQuery 3.  Definitely remove from this material.
